class NoteState:
    ADD_TITLE = 'ADD_TITLE'
    ADD_TEXT = 'ADD_TEXT'
    ADD_DESCRIPTION = 'ADD_DESCRIPTION'

    UPDATE_TITLE = 'UPDATE_TITLE'
    UPDATE_TEXT = 'UPDATE_TEXT'
    UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION'
    DELETE_NOTE = 'DELETE_NOTE'
